### ISSUE TITLE
Unable to install script

### ISSUE THREAD

**Issue by Tahini-123** [inanutshellus/cura-plugin-pause-at-height-filament-swap#4] opened 2022-11-29 12:04 UTC
Hi,
I copied your script to the Scripts directory but it doesnt appear in the menu (Cura 5.1.1). 

Looking at the log I see the following error:

```
2022-11-29 13:56:34,646 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: Exception: Exception occurred while loading post processing plugin: invalid character '·' (U+00B7) (PoorMansPauseAtHeight.py, line 72)
2022-11-29 13:56:34,650 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "/Users/XXXX/Library/Application Support/cura/5.1/scripts/PoorMansPauseAtHeight.py", line 72
2022-11-29 13:56:34,650 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     <title>cura-plugin-pause-at-height-filament-swap/PoorMansPauseAtHeight.py at main · inanutshellus/cura-plugin-pause-at-height-filament-swap · GitHub</title>
2022-11-29 13:56:34,653 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]: Exception: Exception occurred while loading post processing plugin: invalid character '·' (U+00B7) (PoorMansPauseAtHeight.py, line 72)
2022-11-29 13:56:34,654 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:   File "/Users/XXXX/Library/Application Support/cura/5.1/scripts/PoorMansPauseAtHeight.py", line 72
2022-11-29 13:56:34,654 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [221]:     <title>cura-plugin-pause-at-height-filament-swap/PoorMansPauseAtHeight.py at main · inanutshellus/cura-plugin-pause-at-height-filament-swap · GitHub</title>
```

**Comment by Tahini-123** [comment] 2022-11-29 12:36
For the record, the script at [Thingiverse](https://www.thingiverse.com/thing:4160010) you used as a foundation installs without issues

**Comment by johnneerdael** [comment] 2023-05-04 09:44
Hi @Tahini-123, did you clone the repository? I did not and had similar issues, after cloning it and placing it in the correct folder the script runs fine

**Comment by inanutshellus** [comment] 2023-05-13 13:05
Hm, I don't see anything wrong with the file when I scan it. 

There is one unicode character in the file (a degree symbol) on line 119:


$ grep --color='auto' -P -n "[\x80-\xFF]" PoorMansPauseAtHeight.py
119:                    "unit": "°C",

... but your error is about a unicode centerdot on line 72. Maybe try redownloading it?

**Comment by inanutshellus** [comment] 2023-05-13 13:07
Closing this as can't reproduce. Please open a new ticket with more details and i'll get back on it.

**Comment by inanutshellus** [comment] 2023-05-13 13:07
Closing this as can't reproduce. Please open a new ticket with more details and i'll get back on it.

**Closed as not planned by inanutshellus** 2023-05-13 13:07 UTC
